version: '3.1'

services:
  mongo:
    image: mongo
    command: --smallfiles
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1qaz2wsx
      MONGO_INITDB_DATABASE: notes
    volumes:
      - ./src/main/resources/init-db:/docker-entrypoint-initdb.d
