version: '3.1'

services:
  mongodb:
    image: pedront/rvss-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1qaz2wsx
      MONGO_INITDB_DATABASE: notes
  sync-server:
    image: pedront/rvss-sync-server:latest
    environment:
      MONGODB_HOST: mongodb
    ports:
      - 8080:8080
    depends_on:
      - "mongodb"
