apiVersion: batch/v1
kind: Job
metadata:
  name: sync-jmeter
  labels:
    app: sync-jmeter
spec:
  template:
    metadata:
      name: sync-jmeter
    spec:
      containers:
        - image: gcr.io/reactive-test/rvss-jmeter:latest
          name: sync-jmeter
          env:
          - name: SERVER_HOST
            value: %%SERVER_HOST%%
          - name: NUM_THREADS
            value: "4000"
          - name: RAMPUP_PERIOD
            value: "360"
          - name: LOOP_COUNT
            value: "50"
          - name: OUT_DIR
            value: "out/sync/report"
          - name: OUT_RESULTS
            value: "out/sync/results.csv"
          volumeMounts:
          - mountPath: /jmeter/out
            name: jmeter-sync-volume
      restartPolicy: Never
      volumes:
      - name: jmeter-sync-volume
        gcePersistentDisk:
          pdName: jmeter-sync
          fsType: ext4
