apiVersion: batch/v1
kind: Job
metadata:
  name: sync-jmeter
  labels:
    app: sync-jmeter
spec:
  template:
    metadata:
      name: sync-jmeter
    spec:
      containers:
        - image: gcr.io/reactive-vs-synchronous/rvss-jmeter:latest
          name: sync-jmeter
          env:
          - name: SERVER_HOST
            value: 130.211.157.69
          - name: NUM_THREADS
            value: "4000"
          - name: RAMPUP_PERIOD
            value: "360"
          - name: LOOP_COUNT
            value: "50"
          volumeMounts:
          - mountPath: /jmeter/out
            name: jmeter-sync-volume
      restartPolicy: Never
      volumes:
      - name: jmeter-sync-volume
        gcePersistentDisk:
          pdName: jmeter-sync
          fsType: ext4
