apiVersion: batch/v1
kind: Job
metadata:
  name: async-jmeter
  labels:
    app: async-jmeter
spec:
  template:
    metadata:
      name: async-jmeter
    spec:
      containers:
        - image: gcr.io/%%GC_PROJECT%%/rvss-jmeter:latest
          name: async-jmeter
          env:
          - name: SERVER_HOST
            value: %%SERVER_HOST%%
          - name: NUM_THREADS
            value: "4000"
          - name: RAMPUP_PERIOD
            value: "360"
          - name: LOOP_COUNT
            value: "50"
          - name: PROJECT
            value: "%%GC_PROJECT%%"
          - name: BUCKET_NAME
            value: "%%BUCKET_NAME%%"
          - name: REPORT_NAME
            value: "async"
      restartPolicy: Never
