apiVersion: batch/v1
kind: Job
metadata:
  name: sync-jmeter
  labels:
    app: sync-jmeter
spec:
  template:
    metadata:
      name: sync-jmeter
    spec:
      containers:
        - image: gcr.io/async-test/rvss-jmeter:latest
          name: sync-jmeter
          env:
          - name: SERVER_HOST
            value: %%SERVER_HOST%%
          - name: NUM_THREADS
            value: "4000"
          - name: RAMPUP_PERIOD
            value: "360"
          - name: LOOP_COUNT
            value: "50"
          - name: PROJECT
            value: "async-test"
          - name: BUCKET_NAME
            value: "jmeter-bucket-async-test"
          - name: REPORT_NAME
            value: "sync"
      restartPolicy: Never
