apiVersion: batch/v1
kind: Job
metadata:
  name: async-jmeter
  labels:
    app: async-jmeter
spec:
  template:
    metadata:
      name: async-jmeter
    spec:
      containers:
        - image: gcr.io/reactive-vs-synchronous/rvss-jmeter:latest
          name: async-jmeter
          env:
          - name: SERVER_HOST
            value: 35.238.137.4
          - name: NUM_THREADS
            value: "4000"
          - name: RAMPUP_PERIOD
            value: "360"
          - name: LOOP_COUNT
            value: "50"
          volumeMounts:
          - mountPath: /jmeter/out
            name: jmeter-async-volume
      restartPolicy: Never
      volumes:
      - name: jmeter-async-volume
        gcePersistentDisk:
          pdName: jmeter-async
          fsType: ext4
