apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: %%APP_BACKEND%%
  labels:
    app: %%APP_BACKEND%%
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %%APP_BACKEND%%
  template:
    metadata:
      labels:
        app: %%APP_BACKEND%%
    spec:
      containers:
      - name: %%APP_BACKEND%%
        image: %%IMAGE_PREFIX%%/%%IMAGE_NAME%%:%%IMAGE_TAG%%
        ports:
        - containerPort: 8080
