apiVersion: batch/v1
kind: Job
metadata:
  name: %%APP_JMETER%%
  labels:
    app: %%APP_JMETER%%
spec:
  template:
    metadata:
      name: %%APP_JMETER%%
    spec:
      containers:
        - image: %%IMAGE_PREFIX%%/%%IMAGE_NAME%%:%%IMAGE_TAG%%
          name: %%APP_JMETER%%
          env:
          - name: SERVER_HOST
            value: %%SERVER_HOST%%
          - name: NUM_THREADS
            value: "4000"
          - name: RAMPUP_PERIOD
            value: "360"
          - name: LOOP_COUNT
            value: "50"
          - name: PROJECT
            value: "%%GC_PROJECT%%"
          - name: BUCKET_NAME
            value: "%%BUCKET_NAME%%"
          - name: REPORT_NAME
            value: "%%REPORT_NAME%%"
      restartPolicy: Never
