apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend-async
  labels:
    app: backend-async
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-async
  template:
    metadata:
      labels:
        app: backend-async
    spec:
      containers:
      - name: backend-async
        image: gcr.io/reactive-test/rvss-backend:latest
        ports:
        - containerPort: 8080
