apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend-sync
  labels:
    app: backend-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-sync
  template:
    metadata:
      labels:
        app: backend-sync
    spec:
      containers:
      - name: backend-sync
        image: gcr.io/reactive-vs-synchronous/rvss-backend:latest
        ports:
        - containerPort: 8080
