apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sync-server
  labels:
    app: sync-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sync-server
  template:
    metadata:
      labels:
        app: sync-server
    spec:
      containers:
      - name: sync-server
        image: gcr.io/reactive-vs-synchronous/rvss-sync-server:latest
        env:
        - name: MONGODB_HOST
          value: mongodb-sync
        - name: BACKEND_HOST
          value: backend-sync
        ports:
        - containerPort: 8080
